name: app_agent
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_dotenv: ^5.0.2  
  cupertino_icons: ^1.0.6
  envied: ^0.5.4+1
  json_annotation: ^4.0.1
  logging: ^1.2.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^4.0.2
  build_runner: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
  